### ISSUE TITLE
[FIXED] Problem with installing packages

### ISSUE THREAD

**Issue by piotrpalacz** [abenteuerzeit/tenant-talk#33]
### Environment:
- Device: MacBook Pro (Retina, 15-inch, Mid 2015)
- macOs Monterey 12.6.6
- Tester: Piotr Palacz
- Software version: npm 9.5.1 and terminal
- Rate of Reproduction: 15 times

#### Terminal: 
`1`   clone repository: `git clone https://github.com/abenteuerzeit/tenant-talk.git`
`2`   `cd tenant-talk`
`3`   `cd tenant_frontend`
`4`   `npm install`
`5`   It stucks after last package: `acorn-dynamic-import`

### Installing packages lags and stops after last line of dependencies, in the picture below, and starting application is not possible

![Screen Shot 2023-07-04 at 9 14 15 PM](https://github.com/abenteuerzeit/tenant-talk/assets/98075732/79fa0eef-e129-41bc-88ed-319d6888fc00) 

### Level of Bug Severity - Critical 
Collaborators are not able to install proper packages and they cannot start the app to develop new features. 

### Level of Bug Priority
High: Bug must be resolved at the earliest as it affects the system adversely and renders it unusable until it is resolved.

**Comment by piotrpalacz** [comment]
The issue also occurs if your `node_modules` folder and your `package-lock.json` or `yarn. Lock` files are glitched.

If you are on Windows, use the following commands to delete the folder and the two files.

![Screen Shot 2023-07-04 at 11 43 37 PM](https://github.com/abenteuerzeit/tenant-talk/assets/98075732/64c3c314-7c36-4195-9d82-bcadbd911e79)

If you are on macOS or Linux, issue the following commands instead.

![Screen Shot 2023-07-04 at 11 43 43 PM](https://github.com/abenteuerzeit/tenant-talk/assets/98075732/10731d5d-dd85-4a7d-b117-7ccb21c6221b)

**Comment by abenteuerzeit** [comment]
Thank you for your fast action @piotrpalacz 🔥🔥🔥 I appreciate your skill in resolving 🏎️🐛🥾problems on the same day they are discovered. 

Please create a new pull request with the fixed code and I will merge the incoming code from your corrected code into the development branch.

**Comment by abenteuerzeit** [comment]
PR #34 & #35
