### ISSUE TITLE
bug(GitHub Action Failure): DevOps | CI/CD to Gh-Pages

### ISSUE THREAD

**Issue by abenteuerzeit** [abenteuerzeit/tenant-talk#40]
Dependencies lock file is not found in /home/runner/work/tenant-talk/tenant-talk. Supported file patterns: `package-lock.json`, `npm-shrinkwrap.json`, `yarn.lock`

**Environment**: GitHub Actions, Node.js workflow

**Most Recent Commit**: Merge pull request #39 from abenteuerzeit/breadcrumb

**Link to the issue**: [GitHub Action Run](https://github.com/abenteuerzeit/tenant-talk/actions/runs/5480534140/jobs/9983817910)

## Description:

The GitHub Action for the Node.js workflow in the tenant-talk repository failed during the `npm install`, `build`, and `test` step. The failure occurred after the merge of pull request #39 (breadcrumb feature).

[![.github/workflows/azure-webapps-node.yml](https://github.com/abenteuerzeit/tenant-talk/actions/workflows/azure-webapps-node.yml/badge.svg)](https://github.com/abenteuerzeit/tenant-talk/actions/workflows/azure-webapps-node.yml)

## Steps to Reproduce:

Merge a pull request into the main branch.
The GitHub Action for the Node.js workflow is automatically triggered.
The action fails during the `npm install`, `build`, and `test` step.

- [Workflow](https://github.com/abenteuerzeit/tenant-talk/actions/runs/5480534140/workflow)

## Expected Result:

The GitHub Action should successfully complete all steps, including `npm install`, `build`, and `test` step.

Actual Result:

The GitHub Action fails during the `npm install`, `build`, and `test` step.

## Impact:

The failure of the GitHub Action prevents the automatic deployment of the latest changes to an Azure Web App (TODO)

## Screenshots/Logs:

- [Link to the GitHub Action logs](https://github.com/abenteuerzeit/tenant-talk/actions/runs/5480534140/jobs/9983817910)

- [Pipeline Log](https://[pipelines.actions.githubusercontent.com/serviceHosts/a31e2719-85f2-4dea-b19f-987f57a71e44/_apis/pipelines/1/runs/25/signedlogcontent/2?urlExpires=2023-07-06T22%3A13%3A32.9237042Z&urlSigningMethod=HMACV1&urlSignature=qBlBBvEdZnNur%2B8FfCzhOmbADPnL%2F16R65FX7tGZyHQ%3D](https://pipelines.actions.githubusercontent.com/serviceHosts/a31e2719-85f2-4dea-b19f-987f57a71e44/_apis/pipelines/1/runs/25/signedlogcontent/2?urlExpires=2023-07-06T22%3A13%3A32.9237042Z&urlSigningMethod=HMACV1&urlSignature=qBlBBvEdZnNur%2B8FfCzhOmbADPnL%2F16R65FX7tGZyHQ%3D))

## Possible Cause/Solution:

related to a problem with the dependencies or the build script. 

no secret environmental variables implemented yet

**Comment by piotrpalacz** [comment]
`npm install` works after pulling from `development`, I've never used `npm build` or `npm test`. What is this issue about?

**Comment by abenteuerzeit** [comment]
Thanks for your comment @piotrpalacz - it is for the GitHub Actions workflow and the Node.js environment. This workflow is triggered automatically whenever a pull request is merged into the main branch. It performs several steps, including `npm install`, `npm build`, and `npm test` automatically 

`npm install` is used to install all the dependencies required for our project, which you're already familiar with. However, `npm build` and `npm test` are equally important in our context.

The `npm build` command is used to compile our application and get it ready for deployment. It takes our code and dependencies and creates a version of our app that can be served. If this step fails, we won't have a deployable application.

The `npm test` command is used to run any tests we have written for our application. These tests help us ensure that our code is working as expected and that recent changes haven't broken any existing functionality. If our tests fail, it's a sign that something in our application might be broken.

The issue we're facing is that our GitHub Actions workflow is failing during these steps. This prevents us from automatically deploying our latest changes, which is a significant problem for our continuous integration/continuous deployment (CI/CD) process.

The cause of the issue might be related to our dependencies or our build script. I'm also considering the fact that we haven't implemented any secret environmental variables yet or that the packages are ignored

**Comment by piotrpalacz** [comment]
Thanks @abenteuerzeit for your quick and extensive answer. My question is: what should I do about this issue? How can I resolve it?

**Comment by abenteuerzeit** [comment]
I setup a bot to run npm install and create the lockfile

.github/workflows/update-package-lock.yml

At the moment it will trigger on a special branch, but we can change that to dev, the script still needs some modifications though

**Comment by abenteuerzeit** [comment]
Fixed
